package com.example.demo.model;
// Generated 04-may-2021 10:40:51 by Hibernate Tools 5.4.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OpcionesMenu generated by hbm2java
 */
@Entity
@Table(name="opciones_menu")
public class OpcionesMenu implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Integer id;
	
	@Column(name = "id_rol", nullable = true)
	private Integer idRol;
	
	@Column(name = "opcion", nullable = true)
	private String opcion;

	public OpcionesMenu() {
	}

	public OpcionesMenu(Integer idRol, String opcion) {
		this.idRol = idRol;
		this.opcion = opcion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	public String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

}
