package com.example.demo.model;
// Generated 04-may-2021 10:40:51 by Hibernate Tools 5.4.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos")
public class Pedidos implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Integer id;
	
	@Column(name = "id_usuario", nullable = true)
	private Integer idUsuario;
	
	@Column(name = "fecha", nullable = true)
	private Date fecha;
	
	@Column(name = "metodo_pago", nullable = true)
	private String metodoPago;
	
	@Column(name = "estado", nullable = true)
	private String estado;
	
	@Column(name = "num_factura", nullable = true)
	private String numFactura;
	
	@Column(name = "total", nullable = true)
	private Double total;

	public Pedidos() {
	}

	public Pedidos(Date fecha) {
		this.fecha = fecha;
	}

	public Pedidos(Integer idUsuario, Date fecha, String metodoPago, String estado, String numFactura, Double total) {
		this.idUsuario = idUsuario;
		this.fecha = fecha;
		this.metodoPago = metodoPago;
		this.estado = estado;
		this.numFactura = numFactura;
		this.total = total;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getMetodoPago() {
		return this.metodoPago;
	}

	public void setMetodoPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNumFactura() {
		return this.numFactura;
	}

	public void setNumFactura(String numFactura) {
		this.numFactura = numFactura;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

}
